#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

processes=("eww" "feh" "dunst" "bat" "picom")
for process in "${processes[@]}"; do
    if pidof -q "$process"; then
        pkill -x "$process" > /dev/null
    fi
done

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#picom --backend glx &
picom &
~/.config/leftwm/scripts/bat &
~/.config/leftwm/scripts/wall.sh i &
eww open btm_tray -c ~/.config/leftwm/right/eww
eww open tags -c ~/.config/leftwm/right/eww
dunst &
