#!/usr/bin/env bash
wall=$(cat ~/.config/hypr/.wall)
wallc=$(ls ~/.config/hypr/wallpapers | wc -l) && ((wallc -= 1))
case $1 in 
    c)
        ((wall $2= 1))
        if [ "$wall" -ge "$wallc" ]; then
            echo 0 > ~/.config/hypr/.wall
            wall=0
        elif [ "$wall" -le -1 ]; then 
            ((wallc -= 1))
            echo $wallc > ~/.config/hypr/.wall
            wall=$wallc
        else
            echo "$wall" > ~/.config/hypr/.wall
        fi
        swww img ~/.config/hypr/wallpapers/wall$wall.png &;;
    i)
        swww img ~/.config/hypr/wallpapers/wall$wall.png &;;
esac
