#!/usr/bin/env bash

git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
yay -S --needed bspwm sxhkd picom dmenu dunst polybar pulseaudio zsh pavucontrol neofetch alacritty lsd ttf-jetbrains-mono-nerd ttf-font-awesome ttf-roboto papirus-icon-theme xclip polkit-gnome materia-theme lxappearance network-manager-applet xfce4-power-manager nerd-fonts-complete-starship thunar feh firefox xorg-xrandr xorg-xinput xorg-server xorg-xinit gedit ly
systemctl enable ly.service
cd ..
cp -R bspwm $HOME/.config/
cp -R alacritty $HOME/.config/
cp -R neofetch $HOME/.config/
cp -R zsh $HOME/.config/
cp -R .zshrc $HOME/
sudo touch /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
sudo echo "Section "InputClass"
	Identifier "My Mouse"
	MatchIsPointer "yes"
	Option "AccelerationProfile" "-1"
	Option "AccelerationScheme" "none"
	Option "AccelSpeed" "-0.4"
EndSection" >> /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
nano /etc/X11/xorg.conf.d/50-mouse-acceleration.conf





