#!/usr/bin/env bash

git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
yay -S --needed bspwm sxhkd picom dmenu dunst polybar pulseaudio zsh pavucontrol neofetch alacritty ttf-roboto papirus-icon-theme xclip polkit-gnome materia-theme lxappearance network-manager-applet xfce4-power-manager nerd-fonts-complete-starship thunar feh firefox xorg-xrandr xorg-xinput xorg-server xorg-xinit gedit ly
systemctl enable ly.service
cd ..
cp -R bspwm $HOME/.config/
cp -R alacritty $HOME/.config/
cp -R neofetch $HOME/.config/
cp -R zsh $HOME/.config/
cp -R .zshrc $HOME/
sudo touch /usr/share/X11/50-mouse-acceleration.conf
echo "Section "InputClass"
	Identifier "My Mouse"
	MatchIsPointer "yes"
	Option "AccelerationProfile" "-1"
	Option "AccelerationScheme" "none"
	Option "AccelSpeed" "-0.4"
EndSection" >> /usr/share/X11/50-mouse-acceleration.conf
nano /usr/share/X11/50-mouse-acceleration.conf





