#!/usr/bin/env bash
mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
pacstrap /mnt base base-devel linux linux-firmware grub nano networkmanager
genfstab -U -p /mnt >> /mnt/etc/fstab 
cp -R /root/bspwm /mnt/bspwm
arch-chroot /mnt
