#!/bin/bash
# changes the default output device and the icon on polybar
other_sink=$(pacmd list-sinks | awk -v current="$current_sink" '/index:/{i=$0} /index:/{if ($0!=current && !/\* /) { sub(/^index: /, ""); print $2 }}')
state_file=.state
current_state=$(cat "$state_file")

case "$1" in
--ds)
    if [ "$current_state" = "1" ]; then
    pacmd set-default-sink "$other_sink"
    polybar-msg action dsaudio hook 2
    new_state="2"
    else
    pacmd set-default-sink "$other_sink"
    polybar-msg action dsaudio hook 1
    new_state="1"
    fi
    echo "$new_state" > "$state_file";;
--ds-i)
    if [ "$current_state" = "1" ]; then
    sleep 1
    polybar-msg action dsaudio hook 1
    else
    sleep 1
    polybar-msg action dsaudio hook 2
    fi;;
*)
esac