#!/bin/bash
case "$1" in
--mute)
if amixer get Capture | grep '\[off\]' &> /dev/null; then
    polybar-msg action mic hook 2
    amixer -q set Capture toggle
else
    polybar-msg action mic hook 1
    amixer -q set Capture toggle
fi;;
--mic-i)
if amixer get Capture | grep '\[off\]' &> /dev/null; then
    sleep 1
    polybar-msg action mic hook 1
else
    sleep 1
    polybar-msg action mic hook 2
fi;;
*)
esac