#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

processes=("eww" "feh" "dunst")
for process in "${processes[@]}"; do
    if pidof -q "$process"; then
        pkill -x "$process" > /dev/null
    fi
done

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

eww daemon -c ~/.config/leftwm/themes/right/eww-bar &
eww open bar0 -c ~/.config/leftwm/themes/right/eww-bar &
feh --bg-fill $SCRIPTPATH/wall.png
dunst -config ~/.config/bspwm/dunstrc &
