#! /bin/sh
# crolbar
PATH="$HOME/.config/bspwm/scripts:$PATH"

for monitor in $(bspc query -M); do 
bspc monitor $monitor -d {1,2,3,4,5,6,7}
done

bspc config border_width         2
bspc config window_gap          8
bspc config focused_border_color '#A7A4E0'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 20
bspc config automatic_scheme alternate

processes=("picom" "polybar" "sxhkd" "dunst")
for process in "${processes[@]}"; do
  if pidof -q "$process"; then
   pkill -x "$process" > /dev/null; sleep 0.1
  fi
done

picom --config "$HOME"/.config/bspwm/picom.conf &
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
dunst -config "$HOME"/.config/bspwm/dunstrc &
polybar DP-2 -c "$HOME"/.config/bspwm/config.ini &
polybar DP-0 -c "$HOME"/.config/bspwm/config.ini &
feh --bg-fill "$HOME"/.config/bspwm/wallpapers/wall6.png &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
