#! /bin/sh
# crolbar

# Apps
super + {x,r,e,b}
	{alacritty, \
	dmenu_run -nb black -sb '#6600CC', \
	thunar, \
	firefox}

# quit/restart bspwm
super + ctrl + {q,r}
	bspc {quit,wm -r}

# close 
super + shift +  {q,r}
	bspc node {-c,@/ --rotate 90}

# set the window state
super + {d,shift + space,f}
	bspc node -t {tiled,floating,fullscreen}

# focus,switch the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the last desktop,node and switch between tiled/monocle
{super,alt} + {Tab,z}
	bspc {desktop,node} {-f last,-l next}

# change focus on main desktop
super + {1-5}
	bspc desktop -f '^{6-9,10}'

# change focus on second desktop
super + ctrl {1-5}
	bspc desktop -f '^{1-5}'

# sent a node to selected desktop
super + shift + {1-9,0}
	bspc node -d '^{6-9,10,1-5}'

# preselect spawn direction
super + ctrl + {a,s,w,d,space}
	bspc node -p {west,south,north,east,cancel}

# power off,reboot,log out,lock
super + ctrl + alt + shift + {p,r,q,s,l}
	{sudo systemctl poweroff,sudo systemctl reboot,bspc quit,physlock -d && sudo systemctl suspend,physlock -d}
