#! /bin/bash
wall=$(cat ~/.config/bspwm/scripts/.wall)
wallc=$(ls ~/.config/bspwm/wallpapers | wc -l) && ((wallc -= 1))
case $1 in 
    c)
        ((wall $2= 1))
        if [ "$wall" -ge "$wallc" ]; then
            echo 0 > ~/.config/bspwm/scripts/.wall
            wall=0
        elif [ "$wall" -le "-1" ]; then 
            ((wallc -= 1))
            echo $wallc > ~/.config/bspwm/scripts/.wall
            wall=$wallc
        else
            echo $wall > ~/.config/bspwm/scripts/.wall
        fi
        pkill feh
        feh --bg-fill ~/.config/bspwm/wallpapers/wall$wall.png &;;
    i)
        feh --bg-fill ~/.config/bspwm/wallpapers/wall$wall.png &;;
esac