#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

processes=("eww" "feh" "dunst" "bat")
for process in "${processes[@]}"; do
    if pidof -q "$process"; then
        pkill -x "$process" > /dev/null
    fi
done

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

picom &
~/.config/leftwm/scripts/bar.sh bar &
~/.config/leftwm/scripts/bat &
#feh --bg-fill ~/.config/leftwm/right/walls/wall0.png &
feh --bg-fill ~/.config/leftwm/right/walls/wallno1.png &
dunst -config ~/.config/bspwm/dunstrc &
