#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

processes=("eww" "feh" "dunst" "bat" "polybar")
for process in "${processes[@]}"; do
    if pidof -q "$process"; then
        pkill -x "$process" > /dev/null
    fi
done

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

picom  &
~/.config/leftwm/scripts/bat &
~/.config/leftwm/scripts/wall.sh i &
polybar tray -c ~/.config/leftwm/right/config.ini &
eww open tr -c ~/.config/leftwm/right/eww
dunst -config ~/.config/leftwm/dunstrc &
